#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

// Проверяем, завершилась ли установка зависимостей Composer
if (file_exists($maintenance = __DIR__.'/storage/framework/maintenance.php')) {
    require $maintenance;
}

// Регистрируем автозагрузчик классов PSR-4
require __DIR__.'/vendor/autoload.php';

// Запускаем консольное приложение Laravel
$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);